GESTURE_TO_TAG: dict[str, str] = {
    "THUMBS_UP": "[GESTURE:THUMBS_UP][TONE:AFFIRMATIVE]",
    "THUMBS_DOWN": "[GESTURE:THUMBS_DOWN][TONE:NEGATIVE]",
    "POINTING": "[GESTURE:POINTING][INTENT:REFERENTIAL]",
    "WAVING": "[GESTURE:WAVING][INTENT:GREETING]",
}
